version: '3.0'
services:

  server:
    container_name:  "${APP_NAME}-nodejs"
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker-start.sh
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/home/app:cached
    ports:
      - "3333:3333"
    networks:
      - default
    expose:
      - "3333"

  mysql:
    image: 'mysql:5.7'
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adonis
      - MYSQL_USER=root
    volumes:
      - ./docker/db/data:/var/lib/mysql
